<?php

/**
 * @var \AvvyTest\FirstAvvysModule\Block\Test $block
 */

echo $block->sayHello();
?>

<style>
    body {  font-family: arial, sans-serif;  width: 100%;  margin-top: 30px;}
</style>

<p>Manage layouts
    To make layout changes available on every page, modify the default.xml file. For example, layout changes added to app/code/Vendor/Module/view/frontend/layout/default.xml are loaded on all pages. To add layout changes to a specific page, use a layout file that corresponds to the page’s path. For example, changes to the app/code/Vendor/Module/view/frontend/layout/catalog_product_view.xml page are loaded on the product details page.

    Use these layout instructions to:

    Move a page element to another parent element.
    Add content.
    Remove a page element.
    Arrange the element position.
</p>