<div class="wrapper">
  <h2 class="title">Avvys-Carousel</h2>
  <div class="owl-carousel owl-theme owl-center owl-loaded">

    <div class="item">
      <a href="#">
        <img src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/43033/slider_bags.jpg" alt="" />
        <div class="inner"><a href="#">The Erling Bag</a></div>
      </a>
    </div>
    <div class="item black">
      <a href="#">
        <img src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/43033/slider_book_cover.jpg" alt="" />
        <div class="inner"><a href="#">Summer Book Series</a></div>
      </a>
    </div>
    <div class="item">
      <a href="#">
        <img src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/43033/slider_bags.jpg" alt="" />
        <div class="inner"><a href="#">The Erling Bag</a></div>
      </a>
    </div>
    <div class="item black">
      <a href="#">
        <img src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/43033/slider_book_cover.jpg" alt="" />
        <div class="inner"><a href="#">Summer Book Series</a></div>
      </a>
    </div>
    <div class="item">
      <a href="#">
        <img src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/43033/slider_bags.jpg" alt="" />
        <div class="inner"><a href="#">The Erling Bag</a></div>
      </a>
    </div>
    <div class="item black">
      <a href="#">
        <img src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/43033/slider_book_cover.jpg" alt="" />
        <div class="inner"><a href="#">Summer Book Series</a></div>
      </a>
    </div>
    <div class="item">
      <a href="#">
        <img src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/43033/slider_bags.jpg" alt="" />
        <div class="inner"><a href="#">The Erling Bag</a></div>
      </a>
    </div>
    <div class="item black">
      <a href="#">
        <img src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/43033/slider_book_cover.jpg" alt="" />
        <div class="inner"><a href="#">Summer Book Series</a></div>
      </a>
    </div>
    <div class="item">
      <a href="#">
        <img src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/43033/slider_bags.jpg" alt="" />
        <div class="inner"><a href="#">The Erling Bag</a></div>
      </a>
    </div>
    <div class="item black">
      <a href="#">
        <img src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/43033/slider_book_cover.jpg" alt="" />
        <div class="inner"><a href="#">Summer Book Series</a></div>
      </a>
    </div>

  </div>
</div>


<script type="text/x-magento-init" src="jquery.2.min.js">
  {
     "*": {
        "AvvyTest_FirstAvvysModule/js/carousel": {}
      }
 }
</script>