<div class="wrapper">
  <h2 class="title">Avvys-Carousel</h2>
  <div class="owl-carousel owl-theme owl-center owl-loaded">

    <div class="item">
      <a href="http://avvy-shop.shopgo.se/nylon-backpack-tote-bag.html">
        <img  style="width: 256px;  height: 140px; background-size: cover;" src="http://avvy-shop.shopgo.se/pub/media/NYLON_TOTE.jpg" alt="" />
        <div class="inner"><a href="#">NYLON_TOTE</a></div>
      </a>
    </div>
    <div class="item">
      <a href="http://avvy-shop.shopgo.se/reflective-backpack.html">
      <img  style="width: 256px;  height: 140px; background-size: cover;" src="http://avvy-shop.shopgo.se/pub/media/catalog/REFLECTIVE.jpg" alt="" />
        <div class="inner"><a href="#">Reflective_Backpack</a></div>
      </a>
    </div>
    <div class="item">
      <a href="#">
        <img src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/43033/slider_bags.jpg" alt="" />
        <div class="inner"><a href="#">The Erling Bag</a></div>
      </a>
    </div>
    <div class="item black">
      <a href="#">
        <img src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/43033/slider_book_cover.jpg" alt="" />
        <div class="inner"><a href="#">Summer Book Series</a></div>
      </a>
    </div>
    <div class="item">
      <a href="#">
        <img src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/43033/slider_bags.jpg" alt="" />
        <div class="inner"><a href="#">The Erling Bag</a></div>
      </a>
    </div>
    <div class="item black">
      <a href="#">
        <img src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/43033/slider_book_cover.jpg" alt="" />
        <div class="inner"><a href="#">Summer Book Series</a></div>
      </a>
    </div>
    <div class="item">
      <a href="#">
        <img src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/43033/slider_bags.jpg" alt="" />
        <div class="inner"><a href="#">The Erling Bag</a></div>
      </a>
    </div>
    <div class="item black">
      <a href="#">
        <img src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/43033/slider_book_cover.jpg" alt="" />
        <div class="inner"><a href="#">Summer Book Series</a></div>
      </a>
    </div>
    <div class="item">
      <a href="#">
        <img src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/43033/slider_bags.jpg" alt="" />
        <div class="inner"><a href="#">The Erling Bag</a></div>
      </a>
    </div>
    <div class="item black">
      <a href="#">
        <img src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/43033/slider_book_cover.jpg" alt="" />
        <div class="inner"><a href="#">Summer Book Series</a></div>
      </a>
    </div>

  </div>
</div>


<script type="text/x-magento-init" src="jquery.2.min.js">
  {
     "*": {
        "AvvyTest_FirstAvvysModule/js/carousel": {}
      }
 }
</script>