<div class="widget-wrapper">
    <h2 class="title">HOLIDAY FAVORITES©</h2>
    <div class="owl-carousel owl-theme owl-center owl-loaded">

        <div class="item black">
            <a href="http://avvy-shop.shopgo.se/nylon-backpack-tote-bag.html">
                <img style="width: 256px; background-size: cover;" src="http://avvy-shop.shopgo.se/pub/media/NYLON_TOTE.jpg" alt="" />
                <div class="inner"><a href="#">NYLON_TOTE</a></div>
            </a>
        </div>
        <div class="item black">
            <a href="http://avvy-shop.shopgo.se/reflective-backpack.html">
                <img style="width: 256px; background-size: cover;" src="http://avvy-shop.shopgo.se/pub/media/catalog/REFLECTIVE.jpg" alt="" />
                <div class="inner"><a href="#">Reflective_Backpack</a></div>
            </a>
        </div>
        <div class="item black">
            <a href="http://avvy-shop.shopgo.se/nylon-backpack-tote-bag.html">
                <img style="width: 256px; background-size: cover;" src="http://avvy-shop.shopgo.se/pub/media/NYLON_TOTE.jpg" alt="" />
                <div class="inner"><a href="#">NYLON_TOTE</a></div>
            </a>
        </div>
        <div class="item black">
            <a href="http://avvy-shop.shopgo.se/reflective-backpack.html">
                <img style="width: 256px; background-size: cover;" src="http://avvy-shop.shopgo.se/pub/media/catalog/REFLECTIVE.jpg" alt="" />
                <div class="inner"><a href="#">Reflective_Backpack</a></div>
            </a>
        </div>
        <div class="item black">
            <a href="http://avvy-shop.shopgo.se/nylon-backpack-tote-bag.html">
                <img style="width: 256px; background-size: cover;" src="http://avvy-shop.shopgo.se/pub/media/NYLON_TOTE.jpg" alt="" />
                <div class="inner"><a href="#">NYLON_TOTE</a></div>
            </a>
        </div>
        <div class="item black">
            <a href="http://avvy-shop.shopgo.se/reflective-backpack.html">
                <img style="width: 256px; background-size: cover;" src="http://avvy-shop.shopgo.se/pub/media/catalog/REFLECTIVE.jpg" alt="" />
                <div class="inner"><a href="#">Reflective_Backpack</a></div>
            </a>
        </div>
        <div class="widget owl-controls clickable"></div>
    </div>
</div>

<script type="text/x-magento-init" src="jquery.2.min.js">
    {
     "*": {
        "AvvyTest_FirstAvvysModule/js/carousel": {}
      }
 }
</script>